[build]
  command = "npm install --legacy-peer-deps && npm run build:netlify"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--openssl-legacy-provider"
  SKIP_PREFLIGHT_CHECK = "true"

# 重定向规则（用于单页应用）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
