[build]
  # 构建命令
  command = "npm install --legacy-peer-deps && npm run build"
  
  # 构建输出目录
  publish = "build"
  
  # Node.js 版本
  environment = { NODE_VERSION = "16" }

[build.environment]
  # 设置 Node.js 选项以支持旧版 OpenSSL
  NODE_OPTIONS = "--openssl-legacy-provider"
  
  # 跳过预检查
  SKIP_PREFLIGHT_CHECK = "true"
  
  # 生产环境构建
  GENERATE_SOURCEMAP = "false"

# 重定向规则（用于单页应用）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
